### ISSUE TITLE
Undoing animation and bricker leaves bricker model

### ISSUE THREAD

**Issue by richardklingler** [bblanimation/bricker#22]
1. Add a simple sphere, generate a new bricker model and add an animation...
2. Save the blender file, quit blender and reopen the file
3. Remove the animation
4. Initialize bricker and delete the bricker model

The original sphere appears but the bricker model stays as well.

![after_removing_animation_and_bricker](https://user-images.githubusercontent.com/11256235/48978223-99c81a00-f0a8-11e8-9cbf-08cefcf4e764.png)

**Comment by bblanimation** [comment]
Thank you for reporting this issue! I'll address this issue right away – though I'm not yet able to recreate your issue with the steps as you've listed them. Would you mind clarifying for me what kind of animation you added to the sphere (perhaps with the exact steps you followed to add, then remove, the animation)?

**Comment by richardklingler** [comment]
Hello Christopher

Sorry for late reply...attached the blender test file...
I just used the "Standard build" animation preset..

Also in the console I see following when I remove the animation and the bricker model:

`Clearing animation data from 689 objects.
Time Elapsed: 0;0:0;0.02
Traceback (most recent call last):
  File "/Users/klingler/Library/Application Support/Blender/2.79/scripts/addons/assemblme_v1-2-0/buttons/startOver.py", line 44, in poll
    scn, ag = getActiveContextInfo()
  File "/Users/klingler/Library/Application Support/Blender/2.79/scripts/addons/assemblme_v1-2-0/functions/general.py", line 43, in getActiveContextInfo
    ag = scn.aglist[ag_idx]
IndexError: bpy_prop_collection[-1]: out of range.

location: <unknown location>:-1

location: <unknown location>:-1

Deleting: [####################] 100% DONE
`

cheers
richard
[lego_sphere_test.blend.zip](https://github.com/bblanimation/bricker/files/2639322/lego_sphere_test.blend.zip)

**Comment by bblanimation** [comment]
Great, thanks for the info! These issues should be fixed on the master branch – let me know if you're still running into the issue.

**Comment by richardklingler** [comment]
Hello Christopher

The traceback messages are gone...but the result is still the same...the brick model stays in place after removing animation and bricker model.

Installed both Bricker and AssembleMe master branch.

cheers
richard
